### ISSUE TITLE
UserWarning is logged

### ISSUE THREAD

**Issue by trondhindenes** [inyutin/aiohttp_retry#22] opened 2021-01-18 10:17 UTC
when following the example, I get:
`UserWarning: RetryOptions is deprecated, use ExponentialRetry
  warn("RetryOptions is deprecated, use ExponentialRetry")`

It would be good if the examples were written in such a way that they didn't result in warnings logged. Using `aiohttp-retry==2.3`

**Comment by eLvErDe** [comment] 2021-01-19 13:12
Confirmed

**Comment by ddegirmenci** [comment] 2021-01-21 08:12
It's caused by this line: https://github.com/inyutin/aiohttp_retry/blob/v2.3/aiohttp_retry/__init__.py#L184

Fix seems to be in place: https://github.com/inyutin/aiohttp_retry/blob/437a0c8/aiohttp_retry/__init__.py#L184

**Comment by inyutin** [comment] 2021-02-21 13:04
I forgot to update the version in PyPi after the fix was merged. Use v2.3.1 and everything should be fine.
Sorry for long response.

**Closed by inyutin** 2021-02-21 13:04 UTC
